<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MdxLibs.Definitions\MdxLibs.Definitions.csproj" />
  </ItemGroup>
</Project>